import { randomInt }  from '../../helpers/random-int';
import { randomName } from '../../helpers/random-name';

let people = [
	{
		id                : "firstPerson",
		intelligence      : randomInt(15,25),
		conscientiousness : randomInt(15,25),
		growthPotential   : randomInt(10,20),
		name              : randomName(),
		strength          : randomInt(5, 10),
		age               : randomInt(15,30) + 0.1,
		health            : randomInt(50,90),
		foodStored        : randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "secondPerson",
		intelligence      : randomInt(15,25),
		conscientiousness : randomInt(15,25),
		growthPotential   : randomInt(10,20),
		name              : randomName(),
		strength          : randomInt(5, 10),
		age               : randomInt(15,30) + 0.1,
		health            : randomInt(50,90),
		foodStored        : randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "thirdPerson",
		intelligence      : randomInt(15,25),
		conscientiousness : randomInt(15,25),
		growthPotential   : randomInt(10,20),
		name              : randomName(),
		strength          : randomInt(5, 10),
		age               : randomInt(15,30) + 0.1,
		health            : randomInt(50,90),
		foodStored        : randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "fourthPerson",
		intelligence      : randomInt(15,25),
		conscientiousness : randomInt(15,25),
		growthPotential   : randomInt(10,20),
		name              : randomName(),
		strength          : randomInt(5, 10),
		age               : randomInt(15,30) + 0.1,
		health            : randomInt(50,90),
		foodStored        : randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "fifthPerson",
		intelligence      : randomInt(15,25),
		conscientiousness : randomInt(15,25),
		growthPotential   : randomInt(10,20),
		name              : randomName(),
		strength          : randomInt(5, 10),
		age               : randomInt(15,30) + 0.1,
		health            : randomInt(50,90),
		foodStored        : randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: randomInt(1,5) },
		profession        : { name: 'farmer' }
	}
];

export { people }
