let people = [
	{
		id                : "firstPerson",
		intelligence      : helpers.randomInt(15,25),
		conscientiousness : helpers.randomInt(15,25),
		growthPotential   : helpers.randomInt(10,20),
		name              : helpers.randomName(),
		strength          : helpers.randomInt(5, 10),
		age               : helpers.randomInt(15,30) + 0.1,
		health            : helpers.randomInt(50,90),
		foodStored        : helpers.randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: helpers.randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "secondPerson",
		intelligence      : helpers.randomInt(15,25),
		conscientiousness : helpers.randomInt(15,25),
		growthPotential   : helpers.randomInt(10,20),
		name              : helpers.randomName(),
		strength          : helpers.randomInt(5, 10),
		age               : helpers.randomInt(15,30) + 0.1,
		health            : helpers.randomInt(50,90),
		foodStored        : helpers.randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: helpers.randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "thirdPerson",
		intelligence      : helpers.randomInt(15,25),
		conscientiousness : helpers.randomInt(15,25),
		growthPotential   : helpers.randomInt(10,20),
		name              : helpers.randomName(),
		strength          : helpers.randomInt(5, 10),
		age               : helpers.randomInt(15,30) + 0.1,
		health            : helpers.randomInt(50,90),
		foodStored        : helpers.randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: helpers.randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "fourthPerson",
		intelligence      : helpers.randomInt(15,25),
		conscientiousness : helpers.randomInt(15,25),
		growthPotential   : helpers.randomInt(10,20),
		name              : helpers.randomName(),
		strength          : helpers.randomInt(5, 10),
		age               : helpers.randomInt(15,30) + 0.1,
		health            : helpers.randomInt(50,90),
		foodStored        : helpers.randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: helpers.randomInt(1,5) },
		profession        : { name: 'farmer' }
	},
	{
		id                : "fifthPerson",
		intelligence      : helpers.randomInt(15,25),
		conscientiousness : helpers.randomInt(15,25),
		growthPotential   : helpers.randomInt(10,20),
		name              : helpers.randomName(),
		strength          : helpers.randomInt(5, 10),
		age               : helpers.randomInt(15,30) + 0.1,
		health            : helpers.randomInt(50,90),
		foodStored        : helpers.randomInt(5,15),
		appetite          : 0,
		appetiteFulfilled : 1,
		survivalRate      : 1.0,
		growth            : 0,
		hoursWorked       : 0,
		foodProduced      : 0,
		skills            : { farming: helpers.randomInt(1,5) },
		profession        : { name: 'farmer' }
	}
];

export { people }
